### PR TITLE
Exunit tags

### PR DESCRIPTION
**Pull request by mgwidmann**

### CODE REVIEW

**Comment by maryolivier** [comment]
Hello! Wondering if there is anything I can do to help get this merged. Very excited for this feature.

**Comment by nicholasjhenry** [comment]
@mgwidmann could you let me know what the status of this branch is and we'll be happy to finish this up. Thanks!

**Comment by revati** [comment]
What is status about this? When could this be merged? The absence of this feature blocks me for using this library :(

I just forked this project and merged it into. Took, like 5 seconds, as merge conflicts are trivial

**Comment by nicholasjhenry** [comment]
@revati We're dependent on @mgwidmann to give us a status update. If we don't hear from him before the EOY I'll review the related issues and see if it meets the desired requirements.

**Comment by nicholasjhenry** [comment]
@revati As you have branched off from here for your PR's. Do you consider this PR complete? I haven't had a chance to look at it.

**Comment by revati** [comment]
it supports `@some_tag` and `@other_tag value`

then I can run only tagged events `mix test --only some_tag ` or `mix test --only other_tag:value`

`@timeout 1000` also seems to work as expected.

conflicts are trivial version mismatches.

**Comment by mgwidmann** [comment]
Yeah this should be good to go once merge conflicts are resolved, I can't remember why I didn't merge it yet, perhaps just because I was waiting on a release to put it into.

**Pull request merged**
