### PR TITLE
refactor execute function a bit to be more readable

### PR DESCRIPTION
**Pull request by shdblowers**
refactor parts of execute function to make it more readable/maintainable.

### CODE REVIEW

**Comment by mgwidmann** [comment]
Awesome, I had planned to get around to doing something like this! I've done a bit of this work that might conflict now in #2 ... Since that has functionality, do you mind upmerging your improvements with that branch?

**Comment by mgwidmann** [comment]
Hmm on second thought, its dependent upon the gherkin PR so I need to get that one through first... gimme a bit to work that out

**Comment by mgwidmann** [comment]
I fixed the merge conflicts and merged it, if you have more suggestions or code cleanup (or think my merge was done poorly) please submit another PR. Thanks!

**Comment by shdblowers** [comment]
thanks @mgwidmann

I think this project will be really useful for me once its complete, so will be happy to contribute more :smile:

**Pull request merged**
