### PR TITLE
Ensuring each case has a unique name

### LINKED ISSUE #37: ExUnit / Duplicated Scenario Error with Elixir 1.5
ExUnit with Elixir 1.5 now errors when a duplicate case is used.

```
.** (ExUnit.DuplicateDescribeError) describe "Scenario" is already defined in Test.Features.LoginTest
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:122: :erl_eval.exprs/5
    (stdlib) erl_eval.erl:228: :erl_eval.expr/5
    (stdlib) erl_eval.erl:229: :erl_eval.expr/5
```

### PR DESCRIPTION
**Pull request by rawkode**
Fixes #37

### CODE REVIEW

**Review by mgwidmann — CHANGES_REQUESTED** [review]
I think we need to put a number next to it as well so that outlines (which will all share the same name) will also be unique

**Comment by rawkode** [comment]
@mgwidmann Serial number added to runs

**Comment by rawkode** [comment]
Hey @mgwidmann, thoughts on this?

**Comment by rawkode** [comment]
This is preventing a switch to Elixir 1.5, any chance you can scan this agian, @mgwidmann ?

**Comment by lboekhorst** [comment]
This is also blocking our upgrade to Elixir 1.5. Would be great if this could get merged in.

**Review by mgwidmann — APPROVED** [review]

**Comment by mgwidmann** [comment]
Sorry for missing this! I'll merge and release right away.

**Comment by mgwidmann** [comment]
`v0.3.3` released on hex. Sorry again for the delay!

**Comment by rawkode** [comment]
Sweet. Thank you, @mgwidmann

**Comment by lboekhorst** [comment]
Awesome, thanks!

**Comment by rawkode** [comment]
@toddharding You are correct, I've just tested this. I'll be killing sometime at the airport this afternoon, so I'll put together a fix

**Pull request merged**
